name: 🚀 Test & Deploy
on:
  push:

env:
  # Using Nx Cloud is safer
  NX_REJECT_UNKNOWN_LOCAL_CACHE: 0

jobs:
  test:
    name: ✅ Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: nrwl/nx-set-shas@v3
        with:
          # Use current branch as reference (we are not using main)
          main-branch-name: ${{ github.ref_name }}

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Cache Nx
        uses: actions/cache@v3
        with:
          path: .nx/cache
          key: ${{ runner.os }}-nx-${{ github.sha }}
          restore-keys: ${{ runner.os }}-nx

      - uses: pnpm/action-setup@v2
        with:
          version: 8

      - run: pnpm install

      - name: Playwright browsers install
        run: pnpm playwright install --with-deps

      - run: pnpm nx run-many --parallel=4 -t build,lint,test,test-ui

      - uses: actions/upload-artifact@v3
        with:
          name: 📊 Coverage
          path: coverage
          retention-days: 7

      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: 🎭 Playwright Report
          path: dist/.playwright
          retention-days: 7
